name: my_timer
description: "A customizable Flutter timer widget that supports incrementing and decrementing time with callbacks for tick and completion."
version: 1.0.0
homepage: https://github.com/Priyanshu-techind/my_timer

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
# Add assets or fonts if needed in the future
